# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - capita-selecta

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Build and Test fase
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Pytest
        continue-on-error: false
        run: |
          mkdir testresults
          pip install pytest && pytest . --junitxml=./testresults/test-results.xml && pip install pycmd && py.cleanup .

      - name: Upload unit test results to Artifact
        continue-on-error: false
        uses: actions/upload-artifact@v2
        with:
          name: UnitTestResults
          path: ./testresults/test-results.xml
        
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            .
            !venv/
  # Staging fase
  staging:
    needs: build
    name: Deploy to staging
    environment:
        name: staging
        url: ${{ steps.deploy_staging.outputs.webapp-url }}
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts from Build and Test stage
      uses: actions/download-artifact@v2
      with:
        name: python-app
        path: .

    # Deploy to App Service Linux
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      id: deploy-to-webapp
      with:
        app-name: 'capita-selecta'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A25FF9F84F0F4BE59D0AB13152D99AD6 }}
        slot-name: staging
  # Deploying to Production stage
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: staging
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v1
        id: deploy-to-webapp
        with:
          app-name: 'capita-selecta'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A25FF9F84F0F4BE59D0AB13152D99AD6 }}
